# Generated by Django 5.2.11 on 2026-02-22 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("OK", "Aktiv"),
                    ("AUTH_ERROR", "Auth Error"),
                    ("CLONE_ERROR", "Clone Error"),
                ],
                default="OK",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProjectSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_count", models.PositiveIntegerField()),
                ("page_count", models.PositiveIntegerField()),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="dashboard.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-taken_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "taken_at"],
                        name="snapshot_project_taken_idx",
                    ),
                    models.Index(fields=["taken_at"], name="snapshot_taken_idx"),
                ],
            },
        ),
    ]
