# Generated by Django 5.2.11 on 2026-02-22 16:32

import apps.accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='overleaf_token',
            field=apps.accounts.fields.EncryptedTextField(blank=True, help_text='Verschlüsselt gespeicherter Overleaf Git-Token.', null=True, verbose_name='Overleaf Git-Token'),
        ),
    ]
