volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}

services:
  django: &django
    image: ghcr.io/${GHCR_OWNER}/aenderung-durch-austausch:${IMAGE_TAG:-latest}
    entrypoint: /entrypoint
    volumes:
      - production_django_media:/app/aenderung_durch_austausch/media
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    image: ghcr.io/${GHCR_OWNER}/aenderung-durch-austausch-postgres:${IMAGE_TAG:-latest}
    volumes:
      - production_postgres_data:/var/lib/postgresql/18/docker
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    image: ghcr.io/${GHCR_OWNER}/aenderung-durch-austausch-nginx:${IMAGE_TAG:-latest}
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
    ports:
      - "7777:80"
