# Generated by Django 5.2.11 on 2026-04-20 11:04

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, verbose_name='Begriff')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='URL-Kürzel')),
                ('simple_explanation', models.TextField(help_text='Für alle verständlich — kurze Sätze, keine Fachbegriffe.', verbose_name='Erklärung in einfacher Sprache')),
                ('formal_explanation', models.TextField(help_text='Präzise, akademisch, mit Fachbegriffen wo nötig.', verbose_name='Formale Definition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Veröffentlicht')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Definition',
                'verbose_name_plural': 'Definitionen',
                'ordering': ['term'],
            },
        ),
    ]
