# Generated by Django 5.2.11 on 2026-04-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_topicpart_taggit'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='legacy_post_id',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='PK des migrierten MVP-Posts (für Redirect-Backwards-Compat).', null=True, unique=True),
        ),
    ]
