# Generated by Django 5.2.11 on 2026-05-12 13:25

import apps.medienkompetenz.models
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=220,
                        unique=True,
                        verbose_name="URL-Kürzel",
                    ),
                ),
                (
                    "lead",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Kurzer Lead-Text unter dem Titel.",
                        max_length=400,
                        verbose_name="Einleitung",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Reichtext-Inhalt (Quill). Bilder und Videos können eingebettet werden.",
                        verbose_name="Inhalt",
                    ),
                ),
                (
                    "references",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Literatur, Links und Quellenangaben zu diesem Beitrag.",
                        verbose_name="Quellenangaben & Verweise",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.medienkompetenz.models._article_hero_upload_to,
                        verbose_name="Titelbild",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Veröffentlicht"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medienkompetenz_articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medienkompetenz-Beitrag",
                "verbose_name_plural": "Medienkompetenz-Beiträge",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InteractiveBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("ai_image_quiz", "KI-Bild-Quiz"),
                            ("framing_exercise", "Framing-Übung"),
                            ("text_callout", "Hervorhebung"),
                        ],
                        max_length=32,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Titel"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Erklärung für die Leser:innen – wird über den interaktiven Inhalten angezeigt.",
                        verbose_name="Anleitung",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Typ-spezifische Daten (Fragen, Optionen, Bild-Pfade, …).",
                        verbose_name="Konfiguration",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Reihenfolge"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="medienkompetenz.article",
                        verbose_name="Beitrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interaktiver Abschnitt",
                "verbose_name_plural": "Interaktive Abschnitte",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        upload_to=apps.medienkompetenz.models._block_image_upload_to,
                        verbose_name="Datei",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medienkompetenz_uploads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Hochgeladen von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hochgeladenes Bild",
                "verbose_name_plural": "Hochgeladene Bilder",
                "ordering": ["-created_at"],
            },
        ),
    ]
