# Generated by Django 5.2.11 on 2026-05-26 17:56

import apps.medienkompetenz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medienkompetenz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Wird als Banner über dem Titel angezeigt. Empfohlenes Seitenverhältnis 21:9 (z. B. 2100×900 px). Andere Formate werden nicht beschnitten – freie Ränder erscheinen weiß.",
                null=True,
                upload_to=apps.medienkompetenz.models._article_hero_upload_to,
                verbose_name="Titelbild",
            ),
        ),
    ]
